theme: jekyll-theme-cayman
title: NClient
description: Automatic type-safe .Net HTTP client that allows you to call web service API methods using annotated interfaces or controllers

github:
  repository_url: https://github.com/nclient/NClient
  zip_url: https://github.com/nclient/NClient/releases
  another_url: https://www.nuget.org/packages/NClient/
